export const ENDPOINTS = {
    AUTH: 'login',
    RESET_PASSWORD: 'reset-password',
    VERIFY_CODE: 'verify-reset-code',
    CHANGE_PASSWORD: 'change-password',
    DASHBOARD: 'dashboard',
    USUARIO: 'usuario',
    ADMINS: 'admin',
    CONTRATOS: 'contratos',
    MENU: 'menus',
    MENU_ROL: 'menus/rol',
    ASOCIADOS: 'asociados',
    ADHERENTES: 'adherentes',
    FAMILIARES: 'familiares',
    EMPLEADOS: 'empleados',
    SOLICITUDES: 'solicitudes',
    RESERVAS: 'reservas',
    ENCUESTAS: 'encuestas',
    PREGUNTAS: 'preguntas',
    RESPUESTAS: 'respuestas',
    ENCUESTA: 'encuesta',
    ESPACIOS: 'espacios',
    DISPONIBILIDAD_ESPACIO: 'disponibilidad-espacio',
    EVENTOS: 'noticias',
    FAMILIARES_ASOCIADO: 'familiares-asociado',
    FAMILIARES_ADHERENTE: 'familiares-adherente',
    INVITACIONES: 'invitados',
    ACCESOS: 'entradas',
    ESTADOS: 'estados',
    TIPOS: 'tipos',
    ROLES: 'roles',
    MODULOS: 'modulos',
    PERMISOS: 'permisos',
    PERMISOS_ROL: 'permisos/rol',
    RUBROS: 'rubros',
    PAGOS: 'pagos',
}

export const URL_BACK = "http://127.0.0.1:8000";
// export const URL_BACK = "https://www.apiclubsincelejo.prismau.co";